using Unity.VisualScripting;
using UnityEngine;
using System.Collections.Generic;

[RequireComponent(typeof(AudioSource))]
public class Car : MonoBehaviour
{
    public bool IsDead { get; protected set; }
    [Header("Car Properties")]
    public bool Grounded;
    [Tooltip("The potential damage generated by the current velocity of the car")]
    public float Damage;
    [Tooltip("The speed at which the car must travel (See Movement.cs for Player implementation.)")]
    public float Speed;
    [Tooltip("The rate at which speed is resisted. (A truck-like vehicle requires higher speed resistance.")]
    public float SpeedResistance;
    [Tooltip("The speed at which the car must turn.")]
    public float TurnSpeed;
    [Tooltip("The rate at which turning is resisted. (A heavier or fast vehicle requires higher turn resistance.")]
    public float TurnResistance;
    public Boost CurrentBoost;
    [Header("Car Components")]
    public Health health;
    public Movement movement;
    public CarSounds carSounds;
    public Rigidbody physics;

    
    protected Vector3 currentVelocity; // Really meant for use with the BotCar
    int CurrentLap = 1;
    float DistanceFromNextWaypoint;
    AudioSource sound;
    float originalPitch;
    List<Waypoint> completedWaypoints = new List<Waypoint>();
    Waypoint nextWaypoint;
    bool spawnEffectOnLand = false;


    protected virtual void Awake()
    {
        health = GetComponent<Health>();
        movement = GetComponentInParent<Movement>();
        sound = GetComponent<AudioSource>();
        sound.volume = sound.volume / 4;
        //carSounds = GetComponent<CarSoundbank>();
        physics = GetComponent<Rigidbody>();
        originalPitch = sound.pitch;
    }

    protected virtual void FixedUpdate()
    {
        RaycastHit info;
        /*if (Physics.Raycast(transform.position, -transform.up, out info, 1f))
        {
            if (info.transform.gameObject.layer == 7)
            {
                Grounded = true;
            }
            else
            {
                Grounded = false;
            }
        }*/

        IsDead = health.value <= 0;
        DistanceFromNextWaypoint = nextWaypoint ? Vector3.Distance(this.transform.position, nextWaypoint.transform.position) : 0.00f;

        physics.linearDamping = SpeedResistance;
        physics.angularDamping = TurnResistance;
        physics.linearVelocity -= ((transform.up) * Time.deltaTime * 7) + physics.centerOfMass;

        if (CurrentBoost && !CurrentBoost.isActiveAndEnabled)
        {
            CurrentBoost = null;
        }

        if (movement.currentLinearVelocity.magnitude > .1f)
        {
            float newPitch = Mathf.Clamp((((this is PlayerCar) ? movement.currentLinearVelocity.magnitude - movement.currentAngularVelocity.magnitude : currentVelocity.magnitude)) * .05f, .9f, Mathf.Infinity);
            sound.pitch = newPitch;
            PlayInterruptingLoopSound(carSounds.AccelerateLoop);
        }
        else
        {
            sound.pitch = originalPitch;
            PlayInterruptingLoopSound(carSounds.Idle);
        }
    }

    protected virtual void OnCollisionEnter(Collision collision)
    {
        Rigidbody rb = collision.gameObject.GetComponent<Rigidbody>();
        Car otherCar = collision.gameObject.GetComponent<Car>();
        Health otherHealth = collision.gameObject.GetComponent<Health>();

        if (otherCar && Damage > otherCar.Damage && otherCar != this)
        {
            otherCar.health.Damage((Damage - otherCar.Damage) * 2.5f); // This is the collision with another car
            GameFX.instance.SpawnImpactEffect(collision.GetContact(0).point);
        }
        else if (!otherCar && otherHealth)
        {
            otherHealth.Damage(Damage); // This is the collision with a prop or some other GameObject with a health script
            GameFX.instance.SpawnImpactEffect(collision.GetContact(0).point);
        }

        if (collision.gameObject.CompareTag("Prop"))
        {
            if (rb)
            {
                rb.AddRelativeForce(transform.up * Damage * 3, ForceMode.Impulse); // Knocks around GameObjects with physics on them
                GameFX.instance.SpawnImpactEffect(collision.GetContact(0).point);
            }
            else
            {
                health.Damage(Damage / 4);
                GameFX.instance.SpawnImpactEffect(collision.GetContact(0).point);
            }
        }
    }

    private void OnCollisionStay(Collision collision)
    {
        if (collision.gameObject.layer == 7 || collision.gameObject.layer == 0) // Map Layer
        {
            if (Grounded == false)
            {
                Grounded = true;
                if (spawnEffectOnLand)
                {
                    GameFX.instance.SpawnLandingEffect(transform.position);
                }
            }
            else
            {

            }
        }
    }

    private void OnCollisionExit(Collision collision)
    {
        if (collision.gameObject.layer == 7 || collision.gameObject.layer == 0) // Map Layer
        {
            Grounded = false;
            if (Physics.Raycast(transform.localPosition, -transform.up, 2f, 7 | 0) && !Grounded)
            {
                Debug.Log("Spawn that landing effect!!!");
                spawnEffectOnLand = true;
            }
            else
            {
                spawnEffectOnLand = false;
            }
        }
    }

    private void OnTriggerEnter(Collider other)
    {
        if (other.tag.Contains("Boost") && this is PlayerCar)
        {
            Boost boost = other.gameObject.GetComponent<Boost>();

            GiveBoost(boost);
        }
    }

    public void GiveBoost(Boost boost)
    {
        if (boost is HealthBoost)
        {
            health.Give(boost.value);
            this.CurrentBoost.Activate();
        }
        else
        {
            this.CurrentBoost = boost;
            this.CurrentBoost.Activate();
        }
    }

    public Rigidbody GetPhysics()
    {
        if (physics)
        {
            return physics;
        }
        else
        {
            return null;
        }
    }

    public void NextLap()
    {
        CurrentLap++;
    }

    public int GetCurrentLap()
    {
        return CurrentLap;
    }

    public float GetDistanceFromNextWaypoint()
    {
        return DistanceFromNextWaypoint;
    }

    public int GetCompletedWaypoints()
    {
        return completedWaypoints.Count;
    }

    protected virtual void OnDeath()
    {

    }

    protected virtual void Death()
    {
        IsDead = true;
        GameFX.instance.SpawnExplosion(transform.position);
        GameFX.instance.SpawnSmokeStreamEffect(transform.position);
        OnDeath();
    }


    // Sounds


    protected void PlaySound(AudioClip clip)
    {
        sound.PlayOneShot(clip);
    }

    protected void PlayInterruptingSound(AudioClip clip)
    {
        if (sound.isPlaying && sound.clip != clip)
        {
            sound.Stop();
        }
        if (!sound.isPlaying)
        {
            PlaySound(clip);
        }
    }

    protected void PlayLoopingSound(AudioClip clip)
    {
        sound.clip = clip;
        if (!sound.loop)
        {
            sound.loop = true;
        }

        sound.Play();
    }

    protected void PlayInterruptingLoopSound(AudioClip clip)
    {
        if (sound.isPlaying && sound.clip != clip)
        {
            sound.Stop();
        }
        if (!sound.isPlaying)
        {
            PlayLoopingSound(clip);
        }
    }

    // Message Events

    void AddCompletedWaypoints(Waypoint waypoint)
    {
        if (completedWaypoints.Contains(waypoint))
        {
            return;
        } 
        completedWaypoints.Add(waypoint);
    }

    void ClearCompletedWaypoints()
    {
        completedWaypoints.Clear();
    }

    void SetNextWaypoint(Waypoint waypoint)
    {
        nextWaypoint = waypoint;
    }

    public Waypoint GetNextWaypoint()
    {
        return nextWaypoint;
    }
}
