on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - '*'

jobs:
  build:
    env:
      UNITY_PROJECT_PATH: ''
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        include:
          - os: windows-latest
            build-target: StandaloneWindows64
            build-args: ''